// Code generated by "stringer -type=ErrorFault -trimprefix=ErrorFault"; DO NOT EDIT.

package httpc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrorFaultUnknown-0]
	_ = x[ErrorFaultServer-1]
	_ = x[ErrorFaultClient-2]
}

const _ErrorFault_name = "UnknownServerClient"

var _ErrorFault_index = [...]uint8{0, 7, 13, 19}

func (i ErrorFault) String() string {
	if i < 0 || i >= ErrorFault(len(_ErrorFault_index)-1) {
		return "ErrorFault(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrorFault_name[_ErrorFault_index[i]:_ErrorFault_index[i+1]]
}
